version: 3
services:
    api:
        build:
            context: ./
        container_name: api
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-api
        ports:
            - "3000:3000"
    ui:
        depends_on: 
            - api
        restart: always
        container_name: ui
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-ui
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports:
            - "80:80"
