version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x

    commands:
      # Install @angular/cli and app dependencies.
      - echo Installing source NPM dependencies...
      - npm install

      # Set up all necessary/required env variables and Install CodeClimate reporter.
      - export GIT_COMMIT_SHA="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)"
      - export GIT_COMMITTED_AT="$(date +%s)"
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - ./cc-test-reporter before-build

  build:
    commands:
      # Run code quality tools.
      - echo Running code quality checks...
      - npm run eslint
      - npm run server:build

  post_build:
    commands:
      # Upload test coverage report to CodeCov and CodeClimate.
      # - ./cc-test-reporter after-build -t lcov -r $(echo $CODE_CLIMATE_REPORTER_ID) --exit-code $?

cache:
  paths:
    - '/**/*'
