version: 0.2

env:
  variables:
    CLOUDFRONT_APP_URL: "d2jas05u012m4v.cloudfront.net"

phases:
  install:
    runtime-versions:
      nodejs: 14.x

    commands:
      # Get Chrome Information.
      - curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list

      # Update packages.
      - apt-get update -y -q

      # Install Chrome.
      - apt-get -y install google-chrome-stable

      # Install @angular/cli and app dependencies.
      - echo Installing source NPM dependencies...
      - npm install -g @angular/cli
      - cd client
      - npm install

  build:
    commands:
      # FINALLY: Run e2e tests.
      - npm run e2e -- --configuration=production --base-url=${CLOUDFRONT_APP_URL}
